{"name": "test_create_invoice", "status": "broken", "statusDetails": {"message": "TypeError: 'tuple' object is not callable", "trace": "setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9fa527b37044a3db00ef7ca54fc5dc99\")>\ncreate_invoice_test_data = {'customer_name': 'Sachin Tendulkar', 'due_date': 'April 2025, April 10, 2025', 'invoice_date': 'March 2025, March 4, 2025', 'message_on_invoice': 'automation test', ...}\n\n    def test_create_invoice(setup, create_invoice_test_data):\n        driver = setup\n        create_invoice = Create_Invoice(driver)\n    \n        logger.info(\"Test case started for create invoice\")\n        create_invoice.inv_submod_Sales()\n        logger.info(\"Navigated to Sale module\")\n        create_invoice.inv_submod_invoice()\n        logger.info(\"Navigated to Invoice submodule\")\n        create_invoice.inv_create_invoice()\n        logger.info(\"clicked on create invoice button\")\n        time.sleep(3)\n        create_invoice.inv_select_customer(create_invoice_test_data)\n        logger.info(\"customer selected\")\n        time.sleep(2)\n        #create_invoice.inv_select_credit_terms(create_invoice_test_data)\n        logger.info(\"credit terms selected\")\n        #create_invoice.inv_location_of_sale(create_invoice_test_data)\n        logger.info(\"location of sale selected\")\n        #create_invoice.inv_dd_billing(create_invoice_test_data)\n        logger.info(\"billing address selected\")\n        #create_invoice.inv_shippingvia(create_invoice_test_data)\n        logger.info(\"shippingvia address selected\")\n        #create_invoice.inv_shipping_to(create_invoice_test_data)\n        logger.info(\"shippingto address selected\")\n        create_invoice.inv_invoice_date(create_invoice_test_data)\n        logger.info(\"invoice date selected\")\n        create_invoice.inv_shipping_date(create_invoice_test_data)\n        logger.info(\"shipping date selected\")\n        create_invoice.inv_due_date(create_invoice_test_data)\n        logger.info(\"due date selected\")\n>       create_invoice.inv_btn_add_items(create_invoice_test_data)\nE       TypeError: 'tuple' object is not callable\n\ntest_create_invoice.py:41: TypeError"}, "attachments": [{"name": "log", "source": "51628aa5-59da-488f-b953-9650aa848486-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "91fbae50-0a7a-4d61-b0da-2daa232f2060-attachment.txt", "type": "text/plain"}], "start": 1744981097208, "stop": 1744981127200, "uuid": "57788b01-7a78-474a-8134-96a9870e38e0", "historyId": "fc7b2251192f1c8c226df9a8539342f9", "testCaseId": "fc7b2251192f1c8c226df9a8539342f9", "fullName": "test_create_invoice#test_create_invoice", "labels": [{"name": "suite", "value": "test_create_invoice"}, {"name": "host", "value": "LAPTOP-R01C5SG4"}, {"name": "thread", "value": "18028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_invoice"}]}